{{- if .Values.monitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: fleet-monitor
  labels:
    app: fleet-monitor
    component: monitor
spec:
  type: {{ .Values.monitor.service.type }}
  ports:
  - port: {{ .Values.monitor.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fleet-monitor
{{- end }}
